export const QueryKeys = {
	GET_ROOM_LIST: 'GET_TRAVEL_LIST',
	GET_CATEGORY_LIST: 'GET_CATEGORY_LIST',
	GET_PROFILE: 'GET_PROFILE',
	GET_ADDRESS: 'GET_ADDRESS',
	GET_AMENITY_LIST: 'GET_AMENITY_LIST',
	GET_ROOM_DETAIL: 'GET_ROOM_DETAIL',
	GET_RESERVATION_LIST: 'GET_RESERVATION_LIST',
	GET_WISHLIST_LIST: 'GET_WISHLIST_LIST',
}